export const services = [
  {slug:'plumbing-repairs',name:'Everyday plumbing',short:'Little leak. Big relief.',icon:'wrench',desc:'Leaking taps, running toilets, low pressure. Get the everyday things working the way they should.',heading:'Small problems deserve a proper fix.',body:'A dripping faucet or a toilet that will not stop running can make the whole house feel out of sorts. Start with a careful diagnosis, understand the repair options, and agree on the work before it begins.',items:['Faucet and fixture repairs','Toilet repairs and replacements','Accessible water-line leaks','Water-pressure troubleshooting'],expect:'Tell us which fixture is affected, when you first noticed the issue, and whether it happens constantly or only while water is running. A clear photo can help prepare for the visit.',low:150,high:450},
  {slug:'drain-cleaning',name:'Drains & sewer lines',short:'Get back to free-flowing.',icon:'waves',desc:'Slow sinks and stubborn blockages, with a plan that looks beyond the immediate clog.',heading:'A clear drain. A clearer answer.',body:'A slow drain can have more than one cause. The right approach begins with where the blockage is, how often it returns, and whether other fixtures are affected. Recurring problems may call for a camera inspection rather than another temporary fix.',items:['Kitchen and bathroom drain clearing','Recurring blockage diagnosis','Sewer camera inspection planning','Main-line service assessment'],expect:'Let us know if one fixture is slow or several are backing up. Mention any drain chemicals already used so the technician can plan the work safely.',low:200,high:550},
  {slug:'water-heaters',name:'Water heaters',short:'Bring back the hot showers.',icon:'thermometer',desc:'Repair or replace? Understand your options for reliable hot water at home.',heading:'Hot water without the guesswork.',body:'An unexpected cold shower does not always mean a new water heater. Start with the age of the unit, the symptoms, and a professional assessment. If replacement makes sense, compare capacity, installation requirements, and the full installed price.',items:['Hot-water troubleshooting','Tank water-heater replacement','Tankless suitability assessment','Maintenance and installation planning'],expect:'Have the model, approximate age, and a photo of the label ready. Equipment, venting, access, and any required upgrades affect the final price.',low:1500,high:3500},
  {slug:'sump-pumps',name:'Sump & flood protection',short:'A drier basement starts here.',icon:'shield',desc:'Sump pumps, backup options, and practical planning for the water you do not want inside.',heading:'Plan for water before it arrives.',body:'A sump system is easier to assess before the busy spring season. Review the pump, pit, discharge route, and backup options together. The appropriate solution depends on the home and how water reaches it.',items:['Sump-pump condition assessment','Pump replacement','Battery backup options','Discharge-route review'],expect:'Tell us about past basement water, whether a pump is already installed, and where it discharges. We can discuss the scope before recommending equipment.',low:500,high:1400},
  {slug:'renovations',name:'Kitchen & bath renovations',short:'Make the details work beautifully.',icon:'home',desc:'Good-looking fixtures deserve good plumbing behind them. Plan your next space with confidence.',heading:'Built for the way you live.',body:'Beautiful spaces depend on the work you cannot see. Coordinate plumbing early in a kitchen or bathroom project, especially when moving fixtures or changing the layout. A clear scope helps avoid surprises after finishes are in place.',items:['Fixture replacement and installation','Kitchen and bathroom rough-in planning','Sink and faucet upgrades','Coordination with your renovation team'],expect:'Bring measurements, a rough layout, and the fixture models you are considering. We will identify what needs a site visit before a firm quote.',low:600,high:2500},
  {slug:'urgent-plumbing',name:'Urgent plumbing help',short:'When it cannot wait.',icon:'clock',desc:'A burst pipe or active leak needs a clear next step. Prepare the details for a prompt assessment.',heading:'A calm first step when water will not wait.',body:'If there is an active water leak, use the main shutoff only if you can reach it safely. Keep away from standing water near electrical equipment. A service provider needs to know what is happening now so they can assess urgency and availability.',items:['Active water-leak assessment','Burst-pipe repair planning','Urgent fixture isolation','Follow-up repair and prevention'],expect:'Describe where the water is coming from, whether it has stopped, and any access concerns. This concept site does not dispatch technicians; contact an operating local provider for urgent help.',low:250,high:800},
];
export const areas = [
  {slug:'regina',name:'Regina',line:'From the first home to the forever home.',body:'Regina homes do not all have the same plumbing story. A renovation in an established neighbourhood needs a different conversation from a fixture upgrade in a newer home. Share the age of the property and any previous plumbing work so the visit starts with useful context.',focus:'Everyday repairs, recurring drain problems, water heaters, and kitchen or bathroom updates.',note:'We plan around your neighbourhood, parking, and access to the home.'},
  {slug:'white-city',name:'White City',line:'Thoughtful service just east of the city.',body:'Planning a plumbing visit in White City starts with the address, the work, and the right parts. For growing households, water-heater capacity and busy bathrooms are useful topics to discuss alongside the immediate repair.',focus:'Water-heater planning, fixture upgrades, and household plumbing repairs.',note:'Include the property address when requesting availability and any travel charge.'},
  {slug:'emerald-park',name:'Emerald Park',line:'Keep the whole household running.',body:'For an Emerald Park renovation or repair, clear scheduling makes the work easier to fit into the week. Tell us if your project is a small fixture swap or part of a larger renovation, and whether other trades need to be involved.',focus:'Kitchen and bath installations, drain service, and renovation coordination.',note:'Project timelines and fixture selections help shape an accurate estimate.'},
  {slug:'pilot-butte',name:'Pilot Butte',line:'Practical help for your home.',body:'A plumbing quote for a Pilot Butte home should account for the actual equipment and access. If you are unsure which system serves your property, include that in the request instead of guessing. Photos of visible equipment can make the first conversation more productive.',focus:'Plumbing repairs, hot-water equipment, and sump-pump assessments.',note:'We ask about the existing setup before suggesting a repair or replacement.'},
  {slug:'balgonie',name:'Balgonie',line:'The right plan before the trip.',body:'For a Balgonie service visit, a little preparation helps. Share the symptoms, any equipment details, and when someone can provide access. Discuss the travel component of the estimate along with labour and materials.',focus:'Fixture repairs, water-heater replacement, and planned maintenance.',note:'Confirm appointment availability and total visit costs before booking.'},
  {slug:'lumsden',name:'Lumsden',line:'Care that starts with the property.',body:'Every home has its own water-management history. For a Lumsden sump or plumbing assessment, mention previous basement water, changes to the property, and existing pump equipment. A site visit can help establish the appropriate scope.',focus:'Sump-pump options, plumbing repairs, and water-heater planning.',note:'Photos and a record of past issues help guide the initial assessment.'},
  {slug:'grand-coulee',name:'Grand Coulee',line:'Local attention beyond city limits.',body:'A Grand Coulee plumbing project deserves a written scope with equipment, access, and travel taken into account. Combining planned fixture work into one visit may be worth discussing when you request an estimate.',focus:'Planned fixture replacements, everyday repairs, and hot-water upgrades.',note:'Ask about grouping compatible jobs and the availability of required parts.'},
  {slug:'wascana-view',name:'Wascana View',line:'Plumbing that fits your next chapter.',body:'An updated kitchen or bathroom in Wascana View begins with the layout behind the finishes. Before ordering fixtures, discuss compatibility, shutoff access, and whether supply or drainage locations need to change.',focus:'Kitchen and bathroom renovations, fixture upgrades, and water heaters.',note:'Share fixture specifications and your renovation timeline with the request.'},
];
export const posts = [
  {slug:'regina-winter-plumbing-checklist',category:'SEASONAL CARE',title:'A calmer winter starts with a plumbing check.',excerpt:'A practical cold-weather checklist for Regina homeowners, before the first deep freeze.',time:'4 min read',image:'technician',sections:[['Start with the vulnerable spaces','Before colder weather settles in, think about where water lines run through less-heated areas of the home. Walk through the basement and look for drafts near accessible pipes. If you are unsure whether insulation or a repair is appropriate, arrange an assessment before temperatures drop.'],['Know where the water shuts off','Locate the main water shutoff and keep the route to it clear. Make sure the adults in your household know where it is. If it is stuck, leaking, or difficult to reach, ask a plumber to assess it rather than forcing it.'],['Do not improvise with frozen pipes','If a pipe appears frozen, do not use an open flame. If water is present near electrical equipment, keep clear and seek qualified help. The City of Regina provides detailed guidance on preventing and responding to frozen water pipes.'],['Make a short list before you call','Write down which fixtures are affected, when the issue began, and whether there is an active leak. Have your address and access details ready. Sharing those facts gives a service provider a better starting point than a guess at the cause.']],source:'https://utility.regina.ca/home-property/water/water/tips/',sourceLabel:'City of Regina water tips'},
  {slug:'water-heater-repair-or-replace',category:'HOT WATER',title:'Repair or replace your water heater?',excerpt:'Four useful questions to ask before deciding what comes next for your hot water.',time:'3 min read',image:'technician',sections:[['Begin with the symptom','No hot water, unusual sounds, visible water, and an inconsistent temperature are different problems. Note exactly what changed and when. A symptom on its own is not a reliable diagnosis, and an inspection is a better starting point than ordering a replacement.'],['Know what is already installed','A photo of the unit label can identify the model and capacity. Gather the approximate installation date and any service records you have. Keep clear of hot surfaces and do not remove equipment covers to find information.'],['Compare complete options','Ask for the repair scope and the replacement scope in writing. A useful comparison includes equipment, labour, disposal, venting or connection work, and any required upgrades. A headline equipment price is not the same as a finished installation price.'],['Think about the household','The right choice depends partly on how the home uses hot water. A growing household, new bathroom, or different daily schedule can change demand. Ask about suitable capacity and the practical requirements of a tankless system rather than choosing on trend alone.']]},
  {slug:'what-to-ask-plumbing-quote',category:'HOMEOWNER GUIDES',title:'What belongs in a good plumbing quote?',excerpt:'Less fine print. More clarity. Here is what to check before agreeing to the work.',time:'3 min read',image:'kitchen',sections:[['A specific description of the job','A good quote names the fixtures, equipment, and work included. If diagnosis is still needed, the document should distinguish the initial visit from possible repair costs. Ask how unexpected findings will be handled before work begins.'],['Costs you can actually compare','Look for labour, materials, equipment, disposal, travel, taxes, and any permit-related costs that apply. Ask whether the quote is fixed for the stated scope or an estimate that may change, and what would trigger a revision.'],['Credentials and responsibility','Ask for applicable trade credentials, insurance information, and clarity on who will complete the work. Verify relevant information directly with the issuing organization. An attractive badge on a website is not a substitute for a verifiable record.'],['The finish matters too','Discuss cleanup, testing, access, timing, and written warranty terms. Keep a copy of the agreed scope and any approved changes. Being clear before the work starts protects the relationship as much as it protects the budget.']]},
];
export const faqs = [
 ['Do I get a price before work starts?','That is the service model: diagnose the issue, explain the options, and provide a written scope before you approve the work. Prices in this concept are illustrative; an operating business must confirm its actual rates.'],
 ['Which communities are included?','The proposed service area includes Regina, White City, Emerald Park, Pilot Butte, Balgonie, Lumsden, Grand Coulee, and Wascana View. Confirm appointment availability and any travel charge when booking.'],
 ['Can I request a quote online?','Yes. The quote builder prepares a request you can download. This preview does not send requests to a business or book appointments.'],
 ['Are the reviews and photos from real jobs?','No. This is a website concept. Testimonials are clearly marked examples, and the original generated images are illustrative. Verified customer reviews, credentials, and real project photos can replace them before business launch.'],
 ['Does a plumbing problem always need a replacement?','No. The right choice depends on the cause, condition, and scope of the problem. Ask for an assessment and compare the complete repair and replacement options.'],
];
