#!/usr/bin/env node
/**
 * Self-host Google Fonts as woff2 + generate a local @font-face stylesheet.
 *
 * Why this exists: the playbook requires self-hosted fonts (no visitor IP sent to a
 * third party, no extra DNS/TLS handshake before first paint). Running this once
 * vendors the files into src/fonts/ so the built site has zero external font calls.
 *
 * ponytail: plain fetch + regex over the Google CSS. A font-subsetting toolchain
 * (glyphhanger/pyftsubset) would cut another ~30% but needs Python+fonttools; add it
 * only if font bytes ever show up as the LCP bottleneck.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'src', 'fonts');

// A modern UA is required — Google serves .ttf to unrecognised clients and .woff2 to browsers.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

/** Only these subsets ship. en-CA needs latin; latin-ext covers accented client names. */
const KEEP_SUBSETS = ['latin', 'latin-ext'];

const FAMILIES = [
  { css: 'Bricolage+Grotesque:opsz,wght@12..96,400..800', label: 'display' },
  { css: 'Plus+Jakarta+Sans:ital,wght@0,300..800;1,300..800', label: 'body' },
  { css: 'Instrument+Serif:ital@0;1', label: 'editorial' },
];

/** Google labels each @font-face block with a preceding `/* subset *\/` comment. */
function splitBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(css))) blocks.push({ subset: m[1], block: m[2] });
  return blocks;
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const out = [
    '/* Generated by scripts/fonts.mjs — do not edit by hand. Run `npm run fonts` to regenerate. */',
    '',
  ];
  let downloaded = 0;

  for (const family of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${family.css}&display=swap`;
    const css = await fetchText(url);
    const blocks = splitBlocks(css).filter((b) => KEEP_SUBSETS.includes(b.subset));

    if (!blocks.length) throw new Error(`No usable subsets for ${family.css}`);

    for (const { subset, block } of blocks) {
      const srcMatch = block.match(/src:\s*url\((https:\/\/[^)]+\.woff2)\)/);
      if (!srcMatch) {
        throw new Error(
          `Expected woff2 for ${family.label}/${subset} but got: ${block.slice(0, 120)}`
        );
      }
      const remote = srcMatch[1];
      const nameMatch = block.match(/font-family:\s*'([^']+)'/);
      const styleMatch = block.match(/font-style:\s*([a-z]+)/);
      const slug = `${nameMatch[1].toLowerCase().replace(/\s+/g, '-')}-${styleMatch?.[1] ?? 'normal'}-${subset}`;
      const filename = `${slug}.woff2`;

      const bin = Buffer.from(await (await fetch(remote, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(join(OUT_DIR, filename), bin);
      downloaded++;

      out.push(block.replace(remote, `../fonts/${filename}`).trim(), '');
      process.stdout.write(`  ✓ ${filename} (${(bin.length / 1024).toFixed(1)} KB)\n`);
    }
  }

  await writeFile(join(OUT_DIR, 'fonts.css'), out.join('\n'));
  console.log(`\nSelf-hosted ${downloaded} font files -> src/fonts/`);
}

main().catch((err) => {
  console.error(`\nFont vendoring failed: ${err.message}`);
  process.exit(1);
});
