#!/usr/bin/env node
/**
 * Generate every host's security-header config from deploy/headers.config.js.
 *
 * Also audits the built HTML for EXECUTABLE inline scripts. Empirically verified
 * against Chromium: `script-src` is not applied to `<script type="application/
 * ld+json">` — those are data blocks, not script blocks — so JSON-LD needs no
 * hash and the header stays short. Anything that IS executable gets hashed and
 * added, and if that ever happens you will see it in this output rather than
 * discovering it as a blank page after deploy.
 */
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { securityHeaders, CACHE_RULES } from '../deploy/headers.config.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const DEPLOY = join(ROOT, 'deploy');

const cfg = JSON.parse(await readFile(join(ROOT, 'site.config.json'), 'utf8'));

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

/* ------------------------------------------- find executable inline scripts */

const INLINE_RE = /<script([^>]*)>([\s\S]*?)<\/script>/gi;
const files = (await walk(DIST)).filter((f) => f.endsWith('.html'));

const hashes = new Set();
let dataBlocks = 0;

for (const f of files) {
  const html = await readFile(f, 'utf8');
  let m;
  while ((m = INLINE_RE.exec(html))) {
    const [, attrs, body] = m;
    if (/\ssrc=/i.test(attrs)) continue;          // external, covered by 'self'
    if (!body.trim()) continue;

    const type = /type=["']([^"']+)["']/i.exec(attrs)?.[1]?.toLowerCase();
    const isData = type && !/^(text\/javascript|module|application\/javascript)$/.test(type);

    if (isData) { dataBlocks++; continue; }

    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
    console.warn(`  ! executable inline script in ${relative(ROOT, f)} — hashed`);
  }
}

const scriptHashes = [...hashes];
const headers = securityHeaders({ scriptHashes, analytics: cfg.analytics });

/* ------------------------------------------------------------ host configs */

const host = new URL(cfg.seo.siteUrl).host;
const apex = host.replace(/^www\./, '');
const useWww = host.startsWith('www.');

// vercel.json
const vercelJson = {
  $schema: 'https://openapi.vercel.sh/vercel.json',
  cleanUrls: true,
  trailingSlash: true,
  headers: [
    { source: '/(.*)', headers: Object.entries(headers).map(([key, value]) => ({ key, value })) },
    ...CACHE_RULES.filter((r) => !r.path.startsWith('/*')).map((r) => ({
      source: r.path.replace('*', '(.*)'),
      headers: [{ key: 'Cache-Control', value: r.value }],
    })),
  ],
  redirects: [
    {
      source: '/(.*)',
      has: [{ type: 'host', value: useWww ? apex : `www.${apex}` }],
      destination: `https://${host}/$1`,
      permanent: true,
    },
  ],
};

// netlify.toml
const netlifyToml = `# Generated by scripts/hash.mjs — do not edit by hand.

[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
${Object.entries(headers).map(([k, v]) => `    ${k} = "${v}"`).join('\n')}

${CACHE_RULES.filter((r) => !r.path.startsWith('/*'))
  .map((r) => `[[headers]]\n  for = "${r.path}"\n  [headers.values]\n    Cache-Control = "${r.value}"`)
  .join('\n\n')}

# Canonical host — one 301, no chains
[[redirects]]
  from = "https://${useWww ? apex : `www.${apex}`}/*"
  to = "https://${host}/:splat"
  status = 301
  force = true

# Custom 404 must return a real 404, never 200 (soft-404 kills indexing)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
`;

// _headers (Netlify / Cloudflare Pages)
const underscoreHeaders = `# Generated by scripts/hash.mjs — do not edit by hand.
/*
${Object.entries(headers).map(([k, v]) => `  ${k}: ${v}`).join('\n')}

${CACHE_RULES.filter((r) => !r.path.startsWith('/*'))
  .map((r) => `${r.path}\n  Cache-Control: ${r.value}`)
  .join('\n\n')}
`;

// Apache
const htaccess = `# Generated by scripts/hash.mjs — do not edit by hand.
Options -Indexes
ServerSignature Off

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Force HTTPS
  RewriteCond %{HTTPS} !=on
  RewriteRule ^(.*)$ https://${host}/$1 [R=301,L]

  # Canonical host
  RewriteCond %{HTTP_HOST} !^${host.replace(/\./g, '\\.')}$ [NC]
  RewriteRule ^(.*)$ https://${host}/$1 [R=301,L]
</IfModule>

<IfModule mod_headers.c>
${Object.entries(headers).map(([k, v]) => `  Header always set ${k} "${v.replace(/"/g, '\\"')}"`).join('\n')}
  Header always unset X-Powered-By
  Header always unset Server
</IfModule>

ErrorDocument 404 /404.html

<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/svg+xml "access plus 1 year"
  ExpiresByType font/woff2 "access plus 1 year"
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType text/javascript "access plus 1 year"
  ExpiresByType text/html "access plus 0 seconds"
</IfModule>

# Never serve dotfiles or config
<FilesMatch "^\\.|(\\.json|\\.mjs|\\.md)$">
  Require all denied
</FilesMatch>
`;

// nginx
const nginxConf = `# Generated by scripts/hash.mjs — do not edit by hand.
# Include inside your server { } block.

${Object.entries(headers).map(([k, v]) => `add_header ${k} "${v}" always;`).join('\n')}

server_tokens off;

error_page 404 /404.html;

location ~* \\.(woff2|svg|css|js|png|ico)$ {
    add_header Cache-Control "public, max-age=31536000, immutable" always;
${Object.entries(headers).map(([k, v]) => `    add_header ${k} "${v}" always;`).join('\n')}
}

location ~ /\\. { deny all; }
`;

await mkdir(DEPLOY, { recursive: true });
await writeFile(join(ROOT, 'vercel.json'), JSON.stringify(vercelJson, null, 2) + '\n');
await writeFile(join(ROOT, 'netlify.toml'), netlifyToml);
await writeFile(join(DIST, '_headers'), underscoreHeaders);
await writeFile(join(DIST, '.htaccess'), htaccess);
await writeFile(join(DEPLOY, 'nginx.conf'), nginxConf);
await writeFile(join(DIST, '.csp-hashes.json'), JSON.stringify(scriptHashes, null, 2));

console.log(
  `Deploy configs written. ${dataBlocks} JSON-LD data blocks (no hash needed), ` +
  `${scriptHashes.length} executable inline script hash(es).`
);
